# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CzasPracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_przyjscia', models.TimeField()),
                ('czas_wyjscia', models.TimeField()),
                ('calkowity_czas_pracy', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='DzienPracownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_pracy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.CzasPracy')),
            ],
        ),
        migrations.CreateModel(
            name='Kalendarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('uwagi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('stanowisko', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('haslo', models.CharField(max_length=30)),
                ('przelozony_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Przerwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_przerwy', models.TimeField()),
                ('koniec_przerwy', models.TimeField()),
                ('calkowity_czas_przerwy', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Urlop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_urlopu', models.CharField(max_length=30)),
                ('pracownik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Pracownik')),
            ],
        ),
        migrations.AddField(
            model_name='dzienpracownika',
            name='pracownik_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Pracownik'),
        ),
        migrations.AddField(
            model_name='dzienpracownika',
            name='urlop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Urlop'),
        ),
        migrations.AddField(
            model_name='czaspracy',
            name='kalendarz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Kalendarz'),
        ),
        migrations.AddField(
            model_name='czaspracy',
            name='przerwa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Przerwa'),
        ),
    ]
