# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CzasPracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_przyjscia', models.TimeField(auto_now=True)),
                ('czas_wyjscia', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanowisko', models.CharField(max_length=20)),
                ('przelozony_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Pracownik')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Przerwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_przerwy', models.TimeField(auto_now=True)),
                ('koniec_przerwy', models.TimeField(blank=True, null=True)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Urlop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_urlopu', models.DateField(blank=True, null=True)),
                ('koniec_urlopu', models.DateField(blank=True, null=True)),
                ('typ_urlopu', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='czaspracy',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Pracownik'),
        ),
    ]
