# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalendarz',
            name='czy_pracujacy',
            field=models.BooleanField(default=True),
        ),
    ]
