# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czaspracy',
            name='czas_przyjscia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przerwa',
            name='start_przerwy',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
