# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackerapp', '0002_kalendarz_czy_pracujacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czaspracy',
            name='calkowity_czas_pracy',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='czaspracy',
            name='czas_wyjscia',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='czaspracy',
            name='przerwa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Przerwa'),
        ),
        migrations.AlterField(
            model_name='kalendarz',
            name='uwagi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='przelozony_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Pracownik'),
        ),
        migrations.AlterField(
            model_name='przerwa',
            name='calkowity_czas_przerwy',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='przerwa',
            name='koniec_przerwy',
            field=models.TimeField(null=True),
        ),
    ]
