# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackerapp', '0004_auto_20160408_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dzienpracownika',
            name='urlop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetrackerapp.Urlop'),
        ),
    ]
