# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackerapp', '0005_auto_20160409_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlop',
            name='pracownik_id',
        ),
    ]
