# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetrackerapp', '0006_remove_urlop_pracownik_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='haslo',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='pracownik',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
