# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackerapp', '0007_auto_20160412_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czaspracy',
            name='kalendarz_id',
        ),
        migrations.AddField(
            model_name='czaspracy',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Kalendarz',
        ),
    ]
